### PR TITLE
Make ParseErrorKind public and available through ParseError::kind()

### LINKED ISSUE #319: Support introspection of ParseError?
I think it would be great to have some way to poke into `ParseError` to see what kind of error it actually is. Right now the only possibility I see is to compare strings, which is obviously not something I am willing to do. The easiest way to accomplish that would be to make `ParseErrorKind` part of the public interface.

One use case:

A user wants to parse dates, but there are different formats that the incoming data could have. I'd want to let `chrono` take care of the parsing and then tell me that parsing failed, and not something else. And only if that is the case move on to trying a different format. Basically:

```rust
match DateTime::parse_from_str(..., fmts[i]) {
  Ok(dt) => return dt,
  Err(err) if err.kind() == ParseKindError::Invalid {
    continue
  },
  Err(err) => panic("{}", err),
}
```

That's just one example. I am sure there are more. In fact, error types in most crates can be inspected like this and matched on, at least in some form. Also see `std::io::Error` and its `ErrorKind` (which I guess `ParseError` may have been inspired by).

### PR DESCRIPTION
**Pull request by sbrocket**
ParseErrorKind has also been made #[non_exhaustive] to avoid committing
to only the current set of error kinds, i.e. so that it can be expanded
as needed without an SemVer-breaking change.

### Thanks for contributing to chrono!

- [x] Have you added yourself and the change to the [changelog]? (Don't worry
      about adding the PR number)
- [x] If this pull request fixes a bug, does it add a test that verifies that
      we can't reintroduce it?

[changelog]: ../CHANGELOG.md

Fixes #319

### CODE REVIEW

**Comment by Toover** [comment]
I find the PR good but I wonder why there is a notion of "kind" involved whereas a synonymous notion is provided by the "type" system. Can't `ParseError` just be an `enum` and all kinds be values? Sorry if that is a noob question.

**Comment by sbrocket** [comment]
> Can't `ParseError` just be an `enum` and all kinds be values?

Yes, it could have been an enum instead of there being a separate `ParseErrorKind` enum type. Switching it from a struct to an enum now, however, would be a breaking change.

**Comment by Toover** [comment]
> Switching it from a struct to an enum now, however, would be a breaking change.
Sorry I am still learning Rust... Given that it has been private until now, why would it break? Is it because the ABI of a `struct` differs from the one of an `enum`? So the needed memory allocation won't be right with that new version, unless it is recompiled?

**Comment by sbrocket** [comment]
ParseError is already public, and this change simply adds a new method to
that existing type type. ParseErrorKind was not previously public, which is
why it was possible to make it #[non_exhaustive]. If the ParseErrorKind
type was already public, that would be a breaking change.

Also, this is not really a venue meant for general Rust questions. I’d
recommend checking out the Rust Discord if you’ve got more questions, it’s
a good resource:
https://discord.com/invite/rust-lang-community

**Comment by PumpkinSeed** [comment]
Thanks for the contribution, I just run into an issue which solved by this PR, because I can't return ParseResult in one of my functions, because the ParseErrorKind is private and I want to return `Err(ParseError(ParseErrorKind::Invalid))`.

**Comment by sbrocket** [comment]
> Thanks for the contribution, I just run into an issue which solved by this PR, because I can't return ParseResult in one of my functions, because the ParseErrorKind is private and I want to return `Err(ParseError(ParseErrorKind::Invalid))`.

Thank you but I don’t think this change will actually help with that usage. This leaves the field inside the tuple struct private, so I don’t think you would be able to construct your own ParseError value.

**Comment by sbrocket** [comment]
Maintainers, I haven’t resolved the CHANGELOG.md conflict because it isn’t clear if or when this PR will be looked at, and it seemed likely the conflict would reoccur. If you’re ignoring this because of the conflict please let me know and I’ll fix it, otherwise I would appreciate feedback one way or the other. Thanks.

**Comment by ritchie46** [comment]
This would also be a valuable addition for us. We want to match the minimal possible values from contiguous slices of possible matches. Not having to materialize the string errors would save a lot of allocations.

**Comment by Ploppz** [comment]
Why is this not yet merged?

**Comment by djc** [comment]
The previous maintainer left, and other changes have taken priority. Once CI passes I'm happy to review this.

**Comment by Ploppz** [comment]
Looking at the test results, `#[non_exhaustive]` seems to be unsupported in Rust 1.32. Does `chrono` state an MSVR? Is there a reason why tests are using rustc 1.32 - can this be increased to the current stable version?

**Comment by djc** [comment]
Yeah, that's probably an okay solution for now. Probably should add a comment with a `// TODO: MSRV`.

**Comment by Ploppz** [comment]
Feel free to already review my changes https://github.com/sbrocket/chrono/pull/1

**Comment by sbrocket** [comment]
Done, thanks @Ploppz!

**Comment by Ploppz** [comment]
Np! I guess it's up to you to either rebase or merge from `main` to resolve conflicts.

**Comment by sbrocket** [comment]
I’ll leave it up to the maintainer to handle the changelog conflict, since I have no idea when this might be reviewed and would otherwise need to repeatedly resolve conflicts there.

**Comment by djc** [comment]
Please just rebase this and fix the merge conflict. I don't have time to resolve conflicts for every PR -- I will review this pretty soon once it passes CI.

**Comment by sbrocket** [comment]
Ok, rebased (once; hopefully it makes sense that expecting all authors of pending PRs to rebase their PRs every time the changelog is updated by another merged PR is not a very smooth contribution process). CI isn't going to run automatically because of the first-time contributor approval limitation.

**Comment by Ploppz** [comment]
I hope it's not out of place with a gentle reminder. Additional question: can this be included in the next version / what's the timeline for the next version release?

**Comment by djc** [comment]
It should be in the next release. That's mainly waiting for the work in #677 and related PRs. Rest assured that this is still in my GitHub notifications queue and won't be forgotten (that is, no need to remind me again).

**Review by djc — APPROVED** [review]

**Pull request merged**
