### PR TITLE
Fix compiling for wasm32-unknown-emscripten target #519

### PR DESCRIPTION
**Pull request by orion78fr**
I encountered a bug while compiling for the wasm32-unknown-emscripten target (https://github.com/orion78fr/godot_keepass_rust_totp/runs/2742402148?check_suite_focus=true) and it seems I wasn't the only one :  #519 

I don't know if you really need (and how to do) a test for this as it seems that it haven't been caught by your CI.

### CODE REVIEW

**Comment by jcaesar** [comment]
If wasm32-unknown-emscripten is `cfg(unix)`, wouldn't it be better to use the unix mod for it, instead of the stub one? It does compile, but I haven't tested whether it does anything meaningful.

(Nevermind the fact that I submitted a PR to fix the same problem without looking whether somebody already did. Sorry for that.)

**Comment by hoodmane** [comment]
> wouldn't it be better to use the unix mod for it, instead of the stub one? It does compile, but I haven't tested whether it does anything meaningful.

Yes it is better. Emscripten has working implementations of `timegm`, `mktime`, and `localtime_r`.

**Comment by hoodmane** [comment]
Both #574 and #607 make the correct choice to use the unix one on emscripten target but this PR doesn't. Hopefully one of those two PRs can be merged.

**Comment by orion78fr** [comment]
@hoodmane #593 has been merged in the meantime, no need to comment on an old merged PR from 6 month ago

**Comment by hoodmane** [comment]
Ah great, thanks!

**Comment by djc** [comment]
Actually the fix was merged after @hoodmane made their comment and their comment helped me find #593. So thanks for that!

**Pull request merged**
