### PR TITLE
#383 Implement transition functions

### PR DESCRIPTION
**Pull request by liquidscorpio**
Closes: #383 

**Draft Stage**

### CODE REVIEW

**Comment by liquidscorpio** [comment]
@quodlibetor Any early thoughts regarding the overall flow and top level design? Please do involve other members as needed.

**Comment by liquidscorpio** [comment]
@quodlibetor Ping! Did you get a chance to look at this? In case you are occupied feel free to direct me towards some other member who may help. :)

**Comment by liquidscorpio** [comment]
Any follow-ups @quodlibetor? Again, sorry if this feels like pestering. Just wanted to move forwards with this.

**Comment by kooparse** [comment]
Is this PR still active?

**Comment by liquidscorpio** [comment]
@kooparse I am waiting on response from the maintainers.

**Comment by liquidscorpio** [comment]
@quodlibetor  @kooparse I have moved this PR into a new crate https://github.com/liquidscorpio/chrono-utils#installation
Had to change some of the implementation which relied on private APIs as they are not accessible externally but the exposed interface remains the same. 

The docs and examples at:
https://docs.rs/chrono-utilities/0.0.0-alpha1/chrono_utilities/naive/trait.DateTransitions.html

Closing this PR.

**Pull request closed without merging**
