### PR TITLE
Bump version to 0.4.20

### PR DESCRIPTION
**Pull request by djc**
I think it's time to unleash this thing!

Added #731, #747, #744 and #746 to the release notes.

### CODE REVIEW

**Review by esheppa — APPROVED** [review]
Sounds good to me! All the remaining (recent) issues are API-incompatible so it is great to get this out first

**Comment by tdkt** [comment]
Is there a typo in the changelog about minimal compatible rust version? It mentions both 1.32 and 1.52.

**Comment by djc** [comment]
> The minimum supported Rust version for 0.4.20 is 1.32.0, which is intentionally still quite conservative. If you are using chrono 0.4 with a Rust version older than 1.52, we'd like to hear from you since we'd like to further modernize the code base to ease maintenance.

What part of this is unclear?

**Comment by tdkt** [comment]
Sorry, my bad after re-reading it attentively it makes sense.

**Pull request merged**
