### PR TITLE
Month partial ord

### LINKED ISSUE #998: Implement PartialOrd for Month
It would be nice if Month implemented PartialOrd.

For instance, I have a situation where I am aggregating data on a monthly basis, year by year. For that, I have a YearMonth struct like this:

```rust
struct YearMonth {
    year: i32,
    month: Month,
}
```

For the actual calculation, this is then used as key in a `HashMap`, or part of a tuple inside a `Vec`. I then have a situation where I want to find all the `YearMonth` for the last year, which means I have a comparison like `.filter(|year_month| year_month >= current_year_month.month.minus_one_year())` . Since `Month` does not implement `PartialOrd`, I cannot simple derive the implementation for `YearMonth`, but have to implement my own.

### PR DESCRIPTION
**Pull request by Munksgaard**
Also add a few tests to make sure it behaves as expected.

Fixes #998

### CODE REVIEW

**Comment by Munksgaard** [comment]
I hope I did it correctly by basing it on the 0.4.x branch.

**Review by djc — APPROVED** [review]
Yeah, this is great! The MSRV test will fail, but we can ignore that (#995).

**Comment by totikom** [comment]
Is there a reason why `PartialOrd` is derived but `Ord` isn't?

**Comment by Munksgaard** [comment]
> Is there a reason why `PartialOrd` is derived but `Ord` isn't?

Nothing in particular, I think. Shouldn't be hard to add if you need it? Don't know if @djc wants it though.

**Comment by djc** [comment]
Sounds okay to me.

**Comment by totikom** [comment]
Done in https://github.com/chronotope/chrono/pull/1128

**Pull request merged**
