### PR TITLE
fix rfc2822 parsing to allow omitting second

### PR DESCRIPTION
**Pull request by upsuper**

### CODE REVIEW

**Comment by upsuper** [comment]
ping?

**Comment by quodlibetor** [comment]
Thanks! Just verified that this is in fact correct behavior according to RFC2822. (And sorry for the delay, I've been traveling and am catching up on everything.)

**Comment by upsuper** [comment]
@quodlibetor would you mind releasing a new version which includes this fix?

**Comment by quodlibetor** [comment]
I don't have ownership on crates.io, only @lifthrasiir can do a release. I agree that now would be a reasonable time for a 0.4.1.

**Comment by quodlibetor** [comment]
For now you ought to be able to use [`[patch]`](http://doc.crates.io/manifest.html#the-patch-section) for your development/applications like so:

```toml
[patch.crates-io]
chrono = { git = "https://github.com/chronotope/chrono" }
```

**Pull request merged**
