### PR TITLE
Add sub days from 0.4.x v3

### PR DESCRIPTION
**Pull request by esheppa**
Trying this out using `git merge 0.4.x` as per https://github.com/chronotope/chrono/pull/800#issuecomment-1230345807

### CODE REVIEW

**Comment by esheppa** [comment]
The diff now looks identical to that of #800 which is ideal

**Comment by djc** [comment]
So we don't want to rebase or squash, which leaves the option of adding a merge commit... which I guess means we end up with two merge commits? I wonder if we can prevent that somehow...

**Comment by esheppa** [comment]
how would "Rebase and merge" look for this? It would change the commit hashes, but potentially would preserve the details of the merge commit pointing back to the original?

**Comment by djc** [comment]
Hmm, maybe. But actually we can't rebase because GitHub can't deal with the conflicts?

**Comment by esheppa** [comment]
Maybe we can try targeting another branch first to see what happens?

**Comment by djc** [comment]
Sounds good!

**Comment by esheppa** [comment]
Hmm I'd not clicked through the options, as you said, unable to do the rebase (presumably it would work manually, but the main branch is probably protected). I went with the merge - it doesn't actually look too bad, however I should probably avoid using the word "merge" in the message of the first commit, which would make it look better

**Comment by esheppa** [comment]
Maybe just squashing would be better?

**Comment by esheppa** [comment]
squash doesn't look great (test-main-v2). I think the double-merge-commit is the least bad option, and the two merges is a reasonable price to pay for keeping the history linked

**Pull request merged**
