### PR TITLE
Add Serialize/Deserialize for Option<DateTime>

### PR DESCRIPTION
**Pull request by manifest**
This PR for the [issue](https://github.com/chronotope/chrono/issues/301).

### CODE REVIEW

**Comment by manifest** [comment]
I've just added a PR with these new modules:
- ts_nanoseconds_option
- ts_milliseconds_option
- ts_seconds_option

They all reuse current Serializers and Deserializers' Visitors.

**Comment by manifest** [comment]
One test for Rust 1.13.0 fails on

```rust
error: unions are unstable and possibly buggy (see issue #32836)
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.48/src/macros.rs:42:13
    |
42  |             pub $t $i { $($field)* }
    |             ^^^^^^^^^^^^^^^^^^^^^^^^
    | 
   ::: /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.48/src/lib.rs
    |
177 | cfg_if! {
    | - in this macro invocation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile `libc`.
```

I'm not sure where it comes from. It seems unrelated to this PR.

**Comment by quodlibetor** [comment]
yeah that error is coming from libc, the most recent version doesn't support rust 1.13. I'm not sure what the best way to handle that is, but it's not something you have to worry about.

**Comment by manifest** [comment]
@quodlibetor Is there anything that need to be done to have this one merged?

**Comment by promethe42** [comment]
+1 can we merge this?

**Comment by quodlibetor** [comment]
Sorry about the delay, I feel like there ought to be a better way to do this, since currently using an option can be done pretty trivially https://github.com/chronotope/chrono/pull/125#issuecomment-388342995 .

So, (A) I would rather this was already more ergonomic, and (B) maybe it would be better to do something that doesn't add quite as much API surface/code that requires maintenance.

**Comment by promethe42** [comment]
@quodlibetor maybe I missed something but the code in https://github.com/chronotope/chrono/pull/125#issuecomment-388342995 doesn't work for me.

It throws with `Json(Error("missing field `revisionDate`"))` when the field is missing.

IMHO because the proposed code in your comment does not actually handle the case when the field is not here. Which is the whole point behind `Option<DateTime<Utc>>`.

So AFAIK this PR is still required and very useful.

**Comment by promethe42** [comment]
My bad: the suggested solution in https://github.com/chronotope/chrono/pull/125#issuecomment-388342995 works if I add `#[serde(default)]` to the corresponding field.

**Comment by quodlibetor** [comment]
Looks good enough to merge, we can make the code-size smaller in a future commit.

**Pull request merged**
