### PR TITLE
Add sub days from 0.4.x v3

### PR DESCRIPTION
**Pull request by esheppa**
Will redo the commit message for this to remove the word "merge"

### CODE REVIEW

**Comment by djc** [comment]
I guess the double merge option is fine -- just seems crappy that GitHub doesn't have a better way to do this.

**Comment by esheppa** [comment]
lets hold off for a moment as there are a few other options I can try

**Comment by esheppa** [comment]
Actually I guess the only way to meet both requirements:
* avoid double merge commit
* maintain some link to the history

Is to not have a protected main branch, and just do one merge commit. But that seems worse than just having double merge commits - so then the choices become:

* Double merge
* Double rebase (I've done this as `test-main-v3` just to make sure I've tried all the options)

Comparing `test-main`, `test-main-v2` and `test-main-v3` I think `test-main` is the clear winner, as the commits can be tracked back. Alternatively if we want only linear history then `test-main-v3` is better, however the only way to track the commits is by message.

**Comment by djc** [comment]
I think I agree. So is this good to merge?

**Comment by esheppa** [comment]
Yes good to go unless we think its worth rewording the `merge 0.4.x - Add/Sub days` commit message

**Comment by esheppa** [comment]
This is really nice - the `0.4.x` branch shows up as exactly 8 commits behind, and 0 ahead, so that makes the double merge definitely the best choice

**Pull request merged**
