### PR TITLE
Bump version to 0.4.27

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by pitdicker** [comment]
Can you also update `CITATION.cff`?

**Review by pitdicker — APPROVED** [review]
:+1: and thank you.

**Comment by djc** [comment]
Published.

**Comment by djc** [comment]
Not sure if you did it or I did it in the end, but it seems to be published now, thanks for the reminder.

**Comment by pitdicker** [comment]
I am also not sure. I was looking around in how it would work, but didn't press (at least intentionally).

**Pull request merged**
