### PR TITLE
Add `Weekday::days_since`.

### LINKED ISSUE #201: Replace weekday-number methods with a single days_since method
Essentially:

```
number_from_monday() => days_since(Monday) + 1
number_from_sunday() => days_since(Sunday) + 1
num_days_from_monday() => days_since(Monday)
num_days_from_sunday() => days_since(Sunday)
```

If we want to replace `number_from` with something I'd probably go with `days_since_plus_one` or something more explicit.

### PR DESCRIPTION
**Pull request by pitdicker**
This resurrects the work in https://github.com/chronotope/chrono/pull/216 by @clarfonthey.

`WeekDay::days_since` doesn't offer any new functionality, but I quite like its API.

Fixes #201, #1560.

### CODE REVIEW

**Comment by pitdicker** [comment]
Hmm, it must be late :laughing:. I'll fix it to actually work, and merge it with the not-public `WeekDay::num_days_from` that does the same thing.

**Review by djc — COMMENTED** [review]
Can you just squash these commits and make sure that `days_since()` lives underneath the existing methods?

(You can keep the original author around with an `Co-authored-by:` tag in the commit message.)

**Comment by pitdicker** [comment]
'Co-authored-by:` is new for me, I'll have to learn about that.

**Comment by djc** [comment]
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by pitdicker** [comment]
Thank you! It doesn't render special in Git Gui, but I guess this is it...

**Review by djc — APPROVED** [review]

**Pull request merged**
