### PR TITLE
README badge for project license

### PR DESCRIPTION
**Pull request by jtmoon79**
Example at https://github.com/jtmoon79/super-speedy-syslog-searcher/#super-speedy-syslog-searcher-s4-

Why? Badges are are grokkable and just fun eye candy.

### CODE REVIEW

**Comment by pitdicker** [comment]
I do like a little eye candy. To not go too overboard, maybe the badges should be limited to what fits on one line on crates.io?

afbeelding

- The CI badge can maybe be made a little smaller?
- Can docs.rs. show the version number instead of 'passing'?
- Gitter seems pretty desolated, maybe better to remove it?
- The license could be useful, but it repeats information that is already easily visible.
- A badge with downloads (https://github.com/chronotope/chrono/pull/1101) feels a bit like boasting, but part of that is just because chrono is a pretty old crate.
- A badge with commits since (https://github.com/chronotope/chrono/pull/1099) can give some indication of the maintenance status of a crate, but does not paint the whole picture.
- Maybe a badge with the MSRV is useful?
- Is code coverage something we care about?

**Comment by pitdicker** [comment]
Also parts of the readme are really old and don't make much sense anymore :laughing:. But that is another issue.

**Comment by jtmoon79** [comment]
> Gitter seems pretty desolated, maybe better to remove it?
Yeah, it does appear dead. I logged in today and replied to some messages. No activity.

One problem with gitter is I can't get offline notifications (AFAICT).  I have to keep a browser window with gitter open. But I'm not going to do that so I'll never reply to newbie questions in a reasonable time, which is sort of the entire point.

**Comment by pitdicker** [comment]
The gitter badge was added in 2018 in https://github.com/chronotope/chrono/pull/241

**Comment by jtmoon79** [comment]
> A badge with downloads feels a bit like boasting, but part of that is just because chrono is a pretty old crate.

😄

It's in the eye of the beholder IMO. I think it points out that chrono is an important crate. I don't think that's boasting, it's just what it is. Some may perceive this as boasting. 🤷

> A badge with commits since can give some indication of the maintenance status of a crate, but does not paint the whole picture.

Yeah, this one is just a fun statistic. I don't have strong feelings for it.

> Maybe a badge with the MSRV is useful?

That _would_ be useful. Great idea!

> Is code coverage something we care about?

I really like code coverage badges. They give me confidence that the software author(s) cares about code quality which gives me confidence in their software.
But code coverage _is_ a bit of work to setup. From my own project, here's what was required for code coverage:
- [`.github/codecov.yml`](https://github.com/jtmoon79/super-speedy-syslog-searcher/blob/0.6.66/.github/codecov.yml)
- [`.github/rust.yml` job](https://github.com/jtmoon79/super-speedy-syslog-searcher/blob/0.6.66/.github/workflows/rust.yml#L384-L470)
- account at codecov.io that uses github credentials of the project owner

**Comment by jtmoon79** [comment]
Oh wow, check out this `chrono` "badge" (from https://repology.org/)

[Packaging status](https://repology.org/project/rust:chrono/versions)

Not suggesting this one, it's huge and less relevant for crates-distributed projects. Just thought it was fun to look at.

**Comment by pitdicker** [comment]
Yes, thank you for sharing

**Comment by pitdicker** [comment]
> I really like code coverage badges. They give me confidence that the software author(s) cares about code quality which gives me confidence in their software.

The coverage is currently ca 70%. Is that something to advertise?

**Comment by jtmoon79** [comment]
Here are some other fun badges to peruse https://naereen.github.io/badges/

**Comment by jtmoon79** [comment]
> > Maybe a badge with the MSRV is useful?
> 
> That _would_ be useful. Great idea!

I am unable to find such a badge.
This is a good list of badges with links at the bottom https://github.com/Naereen/badges But no _Rust MSRV_ badge.

**Comment by pitdicker** [comment]
Then it is something to do by hand. Example: https://github.com/rust-random/rand/blob/master/README.md?plain=1#L8

**Comment by jtmoon79** [comment]
> Then it is something to do by hand. Example: https://github.com/rust-random/rand/blob/master/README.md?plain=1#L8

Ah, good find.  Yeah that would work.  It just won't have any "badge magic" that automatically picks up the latest MSRV from `Cargo.toml`. But I think the MSRV changes rarely so it shouldn't be a problem.

If you don't commit a PR for it in a few days then I will 😇

**Comment by pitdicker** [comment]
> If you don't commit a PR for it in a few days then I will :innocent:

Feel free to do it

**Comment by djc** [comment]
I don't think we should add more badges right now, just adds clutter and takes focus away from the existing ones.

**Comment by jtmoon79** [comment]
> > Gitter seems pretty desolated, maybe better to remove it?
> > Yeah, it does appear dead. I logged in today and replied to some messages. No activity.
> 
> One problem with gitter is I can't get offline notifications (AFAICT). I have to keep a browser window with gitter open. But I'm not going to do that so I'll never reply to newbie questions in a reasonable time, which is sort of the entire point.

I figured out how to get email notifications.  @pitdicker  can you write a message on gitter?  Don't tag me in it.

**Pull request closed without merging**
