### PR TITLE
Fix format::strftime docs link

### PR DESCRIPTION
**Pull request by frederikhors**
### Thanks for contributing to chrono!

If your feature is semver-compatible, please target the main branch;
for semver-incompatible changes, please target the `0.5.x` branch.

Please consider adding a test to ensure your bug fix/feature will not break in the future.

### CODE REVIEW

**Comment by pitdicker** [comment]
@frederikhors Thank you for the PR.

Could you link to the docs.rs page that has an invalid link? Because according to the CI your change turns a working link into a broken one.

**Comment by frederikhors** [comment]
image

The link is to https://docs.rs/chrono/latest/chrono/datetime/format/strftime/index.html which is 404.

**Comment by pitdicker** [comment]
Strange. In some places I have been replacing such relative path links with the newer module syntax when I touch surrounding code:
```md
[`format::strftime` module](crate::format::strftime)`
```
That should work here too and not break docs.rs.

**Comment by frederikhors** [comment]
Do you mean like I just did now?

**Review by pitdicker — APPROVED** [review]

**Comment by djc** [comment]
Can you rebase this on current main?

**Comment by pitdicker** [comment]
I think we can safely merge without rebasing. The doc change is good.

**Comment by pitdicker** [comment]
Thank you @frederikhors!

**Pull request merged**
