### PR TITLE
Update CI test for wasm32-unknown-unknown to enable wasmbind feature

### LINKED ISSUE #740: wasm32/wasmbind: cannot find function tm_to_datetime in this scope
Compiling at 0903ab1a19426fd43a96ba7f2ed86b9fc08bf292 for target wasm32-unknown-unknown with feature `wasmbind` enabled results in a compilation error:

```
[edtwardy@Hackintosh trunk-test]$ cargo build --target wasm32-unknown-unknown
warning: URL fragment `#0903ab1a` in git URL is ignored for dependency (chrono). If you were trying to specify a specific git revision, use `rev = "0903ab1a"` in the dependency declaration.
    Updating git repository `https://github.com/chronotope/chrono#0903ab1a`
   Compiling chrono v0.4.20-beta.1 (https://github.com/chronotope/chrono#0903ab1a#0903ab1a)
error[E0425]: cannot find function `tm_to_datetime` in this scope
   --> /home/edtwardy/.cargo/git/checkouts/chrono-4fedc6b82b24d624/0903ab1/src/offset/local/stub.rs:17:5
    |
17  |     tm_to_datetime(Timespec::now().local())
    |     ^^^^^^^^^^^^^^ help: a function with a similar name exists: `tm_to_time`
...
199 | fn tm_to_time(tm: &Tm) -> i64 {
    | ----------------------------- similarly named function `tm_to_time` defined here

For more information about this error, try `rustc --explain E0425`.
```

[build-error.log](https://github.com/chronotope/chrono/files/9185552/build-error.log)

### PR DESCRIPTION
**Pull request by AmateurECE**
This PR is to fix #740. All that's been committed so far is a change to the CI configuration that will allow discovering compilation errors like this again in the future. Once a CI run has been scheduled and we have observed the failure in the logs, I will commit the fixing change.

- [ ] Have you added yourself and the change to the [changelog]? (Don't worry
      about adding the PR number)
- [ ] If this pull request fixes a bug, does it add a test that verifies that
      we can't reintroduce it?

[changelog]: ../CHANGELOG.md

### CODE REVIEW

**Review by djc — COMMENTED** [review]
I guess this seems reasonable. Do we always require `--features wasmbind` now for wasm32-unknown-unknown? If so, should we unconditionally enable those dependencies for that target instead to make this easier to work with?

**Comment by AmateurECE** [comment]
Great question! I was thinking about that, too. Seems those features enable functions for working with types like `js_sys::Date` from the rustwasm family of crates. You _can_ use chrono without enabling this feature flag in a `wasm32-unknown-unknown` environment, but I ended up getting surprise `unimplemented!` panics for attempting to call functions of chrono's public interface that depended on this feature under the hood.

That being said, I would support unconditionally enabling this feature for that target, as you suggested.

**Comment by djc** [comment]
> That being said, I would support unconditionally enabling this feature for that target, as you suggested.

Okay, let's do it!

**Comment by djc** [comment]
@esheppa worked on #746, so I think this can be closed. Can you check if current main works for your use case?

**Comment by AmateurECE** [comment]
Looks like https://github.com/chronotope/chrono/pull/746 fixes my issue, thank you very much for checking in! It's safe to close this PR, then.

**Pull request closed without merging**
