### PR TITLE
Merge 0.4.x into main 2023-04-26

### PR DESCRIPTION
**Pull request by pitdicker**
Is it helpful if I open a PR to merge 0.4 with the main branch when the changes become non-trivial?

### CODE REVIEW

**Review by jtmoon79 — APPROVED** [review]
LGTM

**Comment by djc** [comment]
This has conflicts. Can you resolve them? May need to redo the merge...

**Comment by pitdicker** [comment]
Redone the merge. Unfortunate, but now at least we have the most recent commits including the MSRV (+CI) fix.

**Comment by djc** [comment]
Thanks for doing the legwork here!

**Pull request merged**
