### PR TITLE
Upgrade pure-rust-locales to 0.7.0 (0.4.x)

### PR DESCRIPTION
**Pull request by jeremija**
This is an update for v4. PR for main branch is #1287.

Context: https://github.com/cecton/pure-rust-locales/pull/7

### CODE REVIEW

**Comment by jeremija** [comment]
cc @pitdicker since you reviewed the change in `pure-rust-locales`.

**Review by djc — APPROVED** [review]

**Comment by pitdicker** [comment]
Thank you! Good work on pure-rust-locales :+1:

**Comment by jeremija** [comment]
Thanks for merging so quickly! Do you guys maybe know when this change will be published on crates.io?

**Comment by djc** [comment]
I (still) think semver-compatible releases are cheap, so if someone asks for one I'm inclined to just do it.

**Comment by pitdicker** [comment]
I am starting to know your opinions a little :smile:.

**Comment by pitdicker** [comment]
Published as 0.4.31.

**Pull request merged**
