### PR TITLE
Clippy allowances to get the build passing again

### PR DESCRIPTION
**Pull request by dekellum**
Branches are cheap. Hope you don't mind a separate PR for this. See #205 for the rationale.

### CODE REVIEW

**Comment by dekellum** [comment]
Achieves fewer lint issues here:

https://travis-ci.org/chronotope/chrono/jobs/328323840

But note, chrono is still not passing latest clippy cleanly. 

Also even rust stable doesn't know about this lint, see below. Its a warning, so I don't know if it acceptable or if there is a better workaround.

~~~
warning: unknown lint: `const_static_lifetime`
   --> src/lib.rs:394:10
    |
394 | #![allow(const_static_lifetime)]
    |          ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(unknown_lints)] on by default
~~~

**Comment by dekellum** [comment]
I figured out how to scope the lint for cargo-clippy, with 4748225 so I think this can be merged.

**Comment by quodlibetor** [comment]
Yup I was just trying to be nice this is great.

**Comment by dekellum** [comment]
Trying to fix the other cases and get the build green.  Travis seems to be unblocked for MacOS again. I was tempted to change these methods to take references instead but I suspect we don't want a breaking change for this, and its unclear how far that change should go (e.g. Naive counterparts).

**Comment by dekellum** [comment]
MacOS builds still took a long time on Travis CI, but it passed, incl. the Clippy build. If you could merge this, other PR's could be rebased for CI.

**Comment by quodlibetor** [comment]
Thanks!

**Pull request merged**
