### PR TITLE
bincode doesn't have serde feature

### PR DESCRIPTION
**Pull request by ignatenkobrain**
It is built-in.

### CODE REVIEW

**Comment by quodlibetor** [comment]
It looks like [this is only true for bincode 1.0](https://github.com/TyOverby/bincode/blob/ff3dab845a6d2904b009455583da4e67ce3a8a2c/changelist.org) (and [the commit that removed the feature](https://github.com/TyOverby/bincode/commit/ff3dab845a6d2904b009455583da4e67ce3a8a2c#diff-90796f738364edb526dfa13994d2f801).

If you bump the bincode dependency I think we can include this in a forthcoming (hopefully: #146 #159 ) 0.4 release.

**Comment by quodlibetor** [comment]
Actually, reading the git history of bincode does not match the release history at all, [there is no 0.8.0 tag](https://github.com/TyOverby/bincode/tags), even though it was released [on May 2nd](https://crates.io/crates/bincode/0.8.0).

@ignatenkobrain what caused you to notice that the feature is missing?

**Comment by ignatenkobrain** [comment]
@quodlibetor so, I'm packaging crates for Fedora..

I didn't want to package alpha version of bincode, so I took latest "stable" release on crates.io (which is 0.8.0). Then when I tried to build chrono, RPM showed me missing dependency on crate(bincode/serde) and then I just unpacked archive downloaded from crates.io and found that there are no features at all...

You know, people mess up with their git repos, so.... but believe me, features do not exist on 0.8.0 ;)

**Comment by dtolnay** [comment]
I filed https://github.com/TyOverby/bincode/issues/132 to tag the bincode releases. 0.8.0 is indeed the newest one.

**Comment by lifthrasiir** [comment]
Indeed, the PR compiles just fine. I'll merge this. Thank you!

**Pull request merged**
