### PR TITLE
Fixes to parsing and calculation of week numbers

### PR DESCRIPTION
**Pull request by esheppa**
Continuation of https://github.com/chronotope/chrono/pull/921

also fixes a bug reported here: https://github.com/chronotope/chrono/issues/961

### CODE REVIEW

**Comment by djc** [comment]
@esheppa thanks for continuing the old PR here! IMO it would be nice to clean up the commit history such that every commit passes tests (squash a bunch of the fixes into the original fixing commit, squash formatting fixes and `cfg` updates into the first commit), and then this should be good to merge.

One question: should we add a `pub(crate)` method to `NaiveDate` for `weeks_from(Weekday)` so that we have one implementation instead of multiple?

**Comment by esheppa** [comment]
> One question: should we add a pub(crate) method to NaiveDate for weeks_from(Weekday) so that we have one implementation instead of multiple? (If so, that could/should probably be a separate commit.)

This is a great idea, I've added in eb75271 but I'd like to add some more tests and squash them into that commit prior to this being merged

**Comment by djc** [comment]
Looks great!

**Comment by djc** [comment]
@esheppa are you able to continue on this or should I take over?

**Comment by esheppa** [comment]
Will get those tests added now

**Review by djc — APPROVED** [review]

**Pull request merged**
