### PR TITLE
Add support for compilation on wasm32-wasi

### LINKED ISSUE #352: Support for wasm32-wasi
It seems like wasm32-wasi isn't supported, but could very easily be supported by chrono (although I don't quite know what the situation with the time crate is nowadays).

### PR DESCRIPTION
**Pull request by coolreader18**
This just disables `wasmbind` from taking effect on WASI. Resolves #352.

### CODE REVIEW

**Comment by CryZe** [comment]
This doesn‘t really resolve my issue. It‘s a good change, but the idea was to make now() work with WASI.

**Comment by coolreader18** [comment]
It does compile without this, but the presence of wasm-bindgen in the dependency tree at all would add a bunch of `wbindgen` imports that runtimes like wasmtime and wasmer don't provide. I think I did misunderstand the issue, though.

**Comment by quodlibetor** [comment]
I agree that this is an improvement, but we still want some more features to fully close out #352

**Comment by quodlibetor** [comment]
Also thank you very much for the contribution @coolreader18 !

**Pull request merged**
