### PR TITLE
Enable clippy lints up to Rust 1.48

### PR DESCRIPTION
**Pull request by LingMan**
Enables clippy to show lints applicable for Rust versions 1.39..=1.48 and fixes all resulting warnings.

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
Thanks!

**Comment by LingMan** [comment]
Added one more fix for a clippy warning that shows up since Rust 1.66.

**Comment by LingMan** [comment]
Gentle ping.

**Comment by djc** [comment]
@esheppa going to merge this, please feel free to review post-merge.

**Comment by djc** [comment]
Thanks, and sorry for the delay!

**Review by esheppa — COMMENTED** [review]
Looks good!

**Pull request merged**
