### PR TITLE
Use std duration v0.4.x

### PR DESCRIPTION
**Pull request by esheppa**

### CODE REVIEW

**Comment by esheppa** [comment]
still need to patch 74b087f5d7225bf4d005386151b9ce23f0437540 onto this before its ready for any review

**Comment by esheppa** [comment]
Removed `TimeDelta` as per discussion in https://github.com/chronotope/chrono/pull/858#issuecomment-1307129021

**Comment by djc** [comment]
Huh, not sure how I did that but it wasn't on purpose.

**Comment by esheppa** [comment]
Would this be better as three or four seperate PR's? One each for Naive Date, Time, DateTime and potentially DateTime<Tz>? (I think it may be able to be separated out now that we aren't removing the old code

**Comment by djc** [comment]
Probably easier to digest that way!

**Comment by esheppa** [comment]
Closing in favour of https://github.com/chronotope/chrono/pull/895 (and future PRs for NaiveDate updates and (Naive)DateTime updates)

**Pull request closed without merging**
