### PR TITLE
Fix building chrono-fuzz

### PR DESCRIPTION
**Pull request by LingMan**
- Fixes building chrono-fuzz which was broken in https://github.com/chronotope/chrono/pull/806
- (Sneaks in a minor Dependabot nit that doesn't deserve its own CI run)

### CODE REVIEW

**Comment by djc** [comment]
I'd like to have most of these changes (except the first one, which I think wouldn't commit) on 0.4.x (from where we'll merge them to main), would you be able to retarget the PR (and rebase the changes)?

**Comment by LingMan** [comment]
Sure, give me a bit to figure it out.

**Comment by djc** [comment]
I recommend `git rebase -i main`, then killing all except the last three non-commented lines.

**Comment by djc** [comment]
Since most development currently happens on 0.4.x, I would still appreciate such a PR for all the applicable changes.

**Comment by LingMan** [comment]
Here you go: https://github.com/chronotope/chrono/pull/968.
I've dropped those commits from this PR so it now mostly fixes the chrono-fuzz build.

**Review by jtmoon79 — APPROVED** [review]
LGTM

Also see fuzzing-related Issues in Bug #1010 , PR #603 .

**Comment by djc** [comment]
Thanks!

**Pull request merged**
