### PR TITLE
Backport and update CITATION.cff

### PR DESCRIPTION
**Pull request by pitdicker**
I didn't backport it before because I didn't understand the file...

### CODE REVIEW

**Comment by pitdicker** [comment]
There seems to be a bug in my git client where two commits right after each other with the same description but different authors have the same author assigned :shrug:.

I don't care about attribution personally, but fixed it anyway.

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
I wonder if there's an easy bash thing that'll check that the `Cargo.toml` version number and the `CITATION.cff` version number match...

**Comment by pitdicker** [comment]
At least now they live on the same branch when you increase the version number.

I'll have a look, but no promises...

**Comment by pitdicker** [comment]
With AWK it should not be that hard, I'll try to add it to this PR.

**Comment by djc** [comment]
Thanks for looking into it!

**Pull request merged**
