### PR TITLE
Fix Allow parsing of timestamps with additional subsecond precision

### PR DESCRIPTION
**Pull request by jonasbb**
Fixes https://github.com/chronotope/chrono/issues/175

### CODE REVIEW

**Comment by quodlibetor** [comment]
Nice! Could you add a test to `chrono::naive::datetime::test_datetime_parse_from_str` that verifies the behavior as well?

**Comment by quodlibetor** [comment]
actually that method could use both a `%S.%f` and plain `%S` test, if you're willing.

**Comment by jonasbb** [comment]
I have added additional test for each of the %f variants.

**Comment by quodlibetor** [comment]
Awesome, thanks!

**Pull request merged**
