### PR TITLE
Replace "cfg(test)" with "cfg(doctest)" for readme testing

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Rustdoc now passes "doctest" when running in test mode.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Question: I see you support rust 1.13 but `cfg(doctest)` appeared in `1.40`. Should I add a feature to disable it automatically for older versions?

**Comment by quodlibetor** [comment]
Thanks, yes I would prefer it if you could put this behind a feature!

You'll also need to rebase off of master to fix a build problem that got into master.

Hey, sorry it took me awhile

**Comment by GuillaumeGomez** [comment]
Sorry for the missing `fi` (not enough bash script in my life haha).

**Comment by quodlibetor** [comment]
You're very lucky

**Pull request merged**
