### PR TITLE
Implement rockets FromFormValue for naive types

### PR DESCRIPTION
**Pull request by 7omb**
Adds a new rocket feature that implements FromFormValue for
NaiveTime, NaiveDate and NaiveDateTime.

### CODE REVIEW

**Comment by quodlibetor** [comment]
What is the current recommended way to implement `FromFormValue` for external (e.g. chrono) types in rocket codebases in the face of orphan impls? Is everybody just newtyping things?

I'm both a bit nervous about embedding any definition of time formats, and feel kind of like this is the wrong place for this impl, but [@ SergioBenitez has already said they're not going to implement these](https://github.com/SergioBenitez/Rocket/issues/602).

I might be willing to accept this under a renamed `unstable-rocket` feature flag documented as not having any guarantees of continuing to exist between different chrono releases, but that also feels ugly.

Something that might be better would be to create a `rocket-chrono` (or `chrono-rocket`, depending on which organization it goes in) crate that has some `RocketNaiveTime(chrono::NaiveTime)` embedded in them with some reasonable `Into<NaiveDateTIme>` etc impls to at least make the implementations slightly less annoying. My intuition is that this would belong in the rocket org since I can imagine several more of these growing, but I'm open to debate.

**Comment by 7omb** [comment]
Yes, I think newtype wrappers are what everybody is probably doing right now and if you're just start a new project this feels quite clunky. This commit was just a little experiment over the weekend that I want to share and discuss. Since it doesn't fit into rocket right now the obvious/only alternative was chrono. But you're right, it feels misplaced and rocket would definitely be a better place. Even the `unstable-rocket` feature does't feel right. So it's ok for me to close this issue. I think I'll give your idea of the `rocket-chrono` wrapper a shot. Maybe this will converge to a better solution in the near future.

**Comment by quodlibetor** [comment]
@7omb Thanks for the PR! I agree that the current situation with orphan impls in rust is pretty annoying.

If you want to do something generic I can imagine creating a `rocket-formvalue-interop` crate with a bunch of `FromFormValue<___>` newtype wrappers, maybe people want it badly enough that they'll contribute their own newtype wrappers.

**Comment by 7omb** [comment]
That's indeed a good idea. At least support for money and numeric types is missing as well right now.

**Pull request closed without merging**
