### PR TITLE
move more code into internals

### PR DESCRIPTION
**Pull request by esheppa**
My goals here are:
* Move any bitwise and other "internal" style operations into internals.rs (this could be split to modules later)
* Use only methods on the types from internals in naive/date.rs and naive/week.rs
* Given the Mdf::new and Of::new functions return an option, do the validation in the constructor

### CODE REVIEW

**Comment by djc** [comment]
Hah, I was also thinking about wrapping `DateImpl` in a newtype here. In this case, I don't think this needs to be merged into my PR before that gets merged. I'd also request that this is split out into smaller commits (for example, one per bullet point in the PR description?). It would be nice to split renames out from other work, for example.

**Comment by esheppa** [comment]
Good call - I'm even keen to go ahead and split `internals` to modules to get a bit more safety around the constructors

**Comment by djc** [comment]
Makes sense, although I'd prefer inline modules given the size of the internals module.

**Comment by esheppa** [comment]
after putting this in modules the code was looking a bit tangled, so I'm trying out a different path, but will focus on the other PRs first

**Comment by esheppa** [comment]
Closing in favour of https://github.com/chronotope/chrono/pull/882

**Pull request closed without merging**
