### PR TITLE
Bump MSRV to 1.60

### LINKED ISSUE #1344: CI failures in MSRV jobs failing to pick up ahash version
https://github.com/chronotope/chrono/actions/runs/6678120652/job/18148831947?pr=1343

```
Run cargo test --lib \
    Updating crates.io index
error: failed to select a version for the requirement `ahash = "^0.7.0"`
candidate versions found which didn't match: 0.4.8, 0.4.1, 0.4.0, ...
location searched: crates.io index
required by package `hashbrown v0.12.0`
    ... which satisfies dependency `hashbrown = "^0.12"` of package `rkyv v0.7.41`
    ... which satisfies dependency `rkyv = "^0.7.41"` of package `chrono v0.4.31 (/home/runner/work/chrono/chrono)`
Error: Process completed with exit code 101.
```

It's weird because ahash 0.7.7 was released 5 days ago but apparently isn't getting picked up here?

### PR DESCRIPTION
**Pull request by djc**
Fixes #1344, I think.

### CODE REVIEW

**Comment by pitdicker** [comment]
Sorry I have been absent, I'll have a look tomorrow.

**Comment by djc** [comment]
@pitdicker no worries! Friendly ping?

**Comment by pitdicker** [comment]
I am trying to understand the cause of the dependency resolution issue on 1.57.0. It seems to be because ahash 0.7.6 is yanked last week. We used to have 0.7.6 in the dependency tree.

All versions before 0.7.7 have a vulnerability and are yanked: https://github.com/tkaitchuck/aHash/issues/163, fixed in PR https://github.com/tkaitchuck/aHash/pull/175.
But it also pulls in a fix for AVR that updates once_cell to 1.13.1.

Maybe we should get in contact in https://github.com/tkaitchuck/aHash/issues/174 or some other issue before bumping the MSRV?

**Comment by djc** [comment]
I think it's probably because the latest ahash 0.7 release includes use of specific dep: features, which cause Cargo before 1.60 to fail parsing the manifest.

**Comment by djc** [comment]
I feel like it's okay to get to 1.60 at this point. Current Debian stable has 1.63.

**Comment by pitdicker** [comment]
Okay, I'm the last to complain about bumping the MSRV 😄. and Debian is pretty much the one to care about, right?

Do you also want to update the documentation in `README.md` and `lib.rs`?

**Comment by pitdicker** [comment]
If we bump to 1.61 we can start making the methods on `DateTime` const, and remove the workaround from https://github.com/chronotope/chrono/pull/1286/commits/6b3a3143c351f63dd89ddd3e19c811f755173b64.

**Comment by djc** [comment]
Added the `README` and crate root docs changes and bumped to 1.61.

**Comment by djc** [comment]
@pitdicker ping?

**Review by pitdicker — APPROVED** [review]
Sorry, in my memory this was already merged.

**Pull request merged**
